const express = require("express");
const Groq = require("groq-sdk");
const authMiddleware = require("../middleware/authMiddleware");

const router = express.Router();

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY || "",
});

// ==========================================
// FALLBACK RULE-BASED ASSISTANT
// ==========================================

function generateFarmAssistantFallback(message) {
  const text = (message || "").toLowerCase();

  if (text.includes("yellow") && text.includes("leaf")) {
    return "Yellow leaves can happen because of nutrient deficiency, excess water, poor drainage or disease. Check soil moisture and inspect the leaves for spots or insects.";
  }

  if (text.includes("fertilizer") || text.includes("fertiliser")) {
    return "Use fertilizer according to your crop and soil requirements. Avoid excessive fertilizer because it can damage plants and soil.";
  }

  if (
    text.includes("sell") ||
    text.includes("selling") ||
    text.includes("market")
  ) {
    return "You can list your crop in the Farm Trading marketplace, compare prices and negotiate directly with buyers.";
  }

  if (text.includes("price") || text.includes("profit")) {
    return "Compare current market prices, production cost, transportation cost and buyer offers before deciding your selling price.";
  }

  if (
    text.includes("pest") ||
    text.includes("insect") ||
    text.includes("bug")
  ) {
    return "Inspect the affected leaves and stems first. Identify the pest before applying any treatment.";
  }

  if (text.includes("crop") || text.includes("plant")) {
    return "You can use the Weather & Crop Advisor to check suitable crops based on weather and soil conditions.";
  }

  return "I can help with crops, farming, market prices, crop selling, pests, fertilizer and Farm Trading features.";
}

// ==========================================
// FARMER ASSISTANT API (Groq AI)
// ==========================================

router.post("/chat", authMiddleware, async (req, res) => {
  try {
    const { message } = req.body;

    if (!message || !message.trim()) {
      return res.status(400).json({
        success: false,
        message: "Message is required",
      });
    }

    if (!process.env.GROQ_API_KEY) {
      console.warn("⚠️ GROQ_API_KEY not set. Using fallback assistant.");
      const fallbackReply = generateFarmAssistantFallback(message);
      return res.json({
        success: true,
        reply: fallbackReply,
        answer: fallbackReply,
      });
    }

    const candidateModels = [
      process.env.GROQ_MODEL,
      "llama-3.3-70b-versatile",
      "openai/gpt-oss-120b",
      "groq/compound-mini",
    ].filter(Boolean);

    let reply = null;
    let lastError = null;

    for (const model of candidateModels) {
      try {
        const completion = await groq.chat.completions.create({
          messages: [
            {
              role: "system",
              content:
                "You are a helpful AI agricultural assistant for the Farm Trading platform. Provide concise, practical, and farmer-friendly advice about crops, farming practices, pest management, market pricing, weather considerations, and sustainable agriculture.",
            },
            {
              role: "user",
              content: message,
            },
          ],
          model,
        });

        reply = completion.choices[0]?.message?.content || null;
        if (reply) break;
      } catch (err) {
        lastError = err;
        if (
          err.status === 404 ||
          (err.message && err.message.toLowerCase().includes("not found")) ||
          (err.message && err.message.toLowerCase().includes("does not exist"))
        ) {
          console.warn(`Groq model ${model} not available, trying next fallback...`);
          continue;
        }
        throw err;
      }
    }

    if (!reply && lastError) {
      throw lastError;
    }

    reply = reply || "No response generated";

    res.json({
      success: true,
      reply,
      answer: reply,
    });
  } catch (error) {
    console.error("Groq AI Error:", error);

    // Graceful fallback to avoid breaking UI experience
    try {
      const fallbackReply = generateFarmAssistantFallback(req.body.message || "");
      return res.json({
        success: true,
        reply: fallbackReply,
        answer: fallbackReply,
        note: "Response generated by fallback assistant due to AI service issue.",
      });
    } catch (fallbackErr) {
      res.status(500).json({
        success: false,
        message: "AI assistant failed to generate a response",
      });
    }
  }
});

// ==========================================
// CROP QUALITY ANALYSIS
// ==========================================

router.post("/crop-quality", authMiddleware, async (req, res) => {
  try {
    const { imageName, cropName } = req.body;

    if (!imageName) {
      return res.status(400).json({
        success: false,
        message: "Crop image is required",
      });
    }

    /*
        Prototype AI analysis.

        Later this function can be replaced
        with an actual computer vision model.
      */

    const qualityResults = [
      {
        quality: "Good",
        confidence: 92,
        freshness: "High",
        recommendation:
          "Crop appears suitable for selling. Store it properly and avoid excessive moisture.",
      },
      {
        quality: "Medium",
        confidence: 78,
        freshness: "Medium",
        recommendation:
          "Crop appears usable but should be sold soon. Check for minor damage or discoloration.",
      },
      {
        quality: "Poor",
        confidence: 65,
        freshness: "Low",
        recommendation:
          "Crop may have visible quality issues. Inspect carefully before selling.",
      },
    ];

    // Deterministic demo result
    const fileScore = imageName.length % 3;

    const result = qualityResults[fileScore];

    res.json({
      success: true,
      cropName: cropName || "Unknown Crop",
      quality: result.quality,
      confidence: result.confidence,
      freshness: result.freshness,
      recommendation: result.recommendation,
      analyzedAt: new Date(),
    });
  } catch (error) {
    console.error("Crop quality error:", error);

    res.status(500).json({
      success: false,
      message: "Crop quality analysis failed",
    });
  }
});

module.exports = router;
